# -*- coding: utf-8 -*-
"""
Created on Sun Oct 13 18:45:16 2019

@author: Yusef Quinlan
"""

#A for loop is a loop that terminates after a predetermined amount of loops
# I.e. we want to run the same code 50 times so we declare that we want to run a loop
# 50 times and then run it.

#Setting the variables for a for loop (Not all for loops need this)
Game_Score_list = []
Game_Score = 0

#Adding a game score for each of 28 turns of a game to the Game_Score list
#The score has not been generated by a complex algorithm and is generally thought
# To increase by 1.6 per turn with a start value of 0, to make things simple.
for Turn in range(0,28):
    Game_Score = Game_Score + 1.6
    Game_Score_list.append(Game_Score)

#Print the scores list and the length of the list.
print(Game_Score_list)
print(len(Game_Score_list))

#Print each item in Game_Score_list, notice that item is assigned to the value of
# the item at index number of the iteration and is not the value of the iteration number.
for item in Game_Score_list:
    print(item)

#Print the turn number and the score for each turn in range 0- length of Game_Score_list
# i.e. the max amount of turns in the list
for turn in range(0, len(Game_Score_list)):
    print("this is turn number : " + str(turn + 1))
    print("Score is: " + str(Game_Score_list[turn]))

#setting up variables for a more complex 'for loop'
Players = ["Jenny", "Andrew"]
TurnNo = 0
Game_Turns = []

#The loop runs 50 times, and adds a player name each turn, it adds a different player name
# each turn , either 'Jenny' or 'Andrew' I won't explain how it works as it is worth
#figuring that out.
for turn in range(0, 50):
    if turn == TurnNo:
        Game_Turns.append(Players[0])
    elif turn == TurnNo + 1:
        Game_Turns.append(Players[1])
        TurnNo = turn + 1

#print the turn numbers and the player associated with the turn.
for turn in range(0, len(Game_Turns)):
    print("this is turn number : " + str(turn + 1))
    print("The player is: " + str(Game_Turns[turn]))